//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAVORITO
    {
        public int USU_RUT { get; set; }
        public int PUB_ID_PUBLICACION { get; set; }
        public int FAV_ID_FAVORITO { get; set; }
    
        public virtual PUBLICACION PUBLICACION { get; set; }
    }
}
