//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASCOTA
    {
        public int ID_MAS { get; set; }
        public string RAZA { get; set; }
        public Nullable<int> EDAD { get; set; }
        public string ESPECIE { get; set; }
        public string NOMBRE { get; set; }
        public double TAMAÑO { get; set; }
    
        public virtual ADOPCION ADOPCION { get; set; }
        public virtual PUBLICACION PUBLICACION { get; set; }
    }
}
