//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASCOTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MASCOTA()
        {
            this.PUBLICACION1 = new HashSet<PUBLICACION>();
        }
    
        public int ID_MAS { get; set; }
        public string RAZA { get; set; }
        public Nullable<int> EDAD { get; set; }
        public string ESPECIE { get; set; }
        public string NOMBRE { get; set; }
        public double TAMAÑO { get; set; }
    
        public virtual ADOPCION ADOPCION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PUBLICACION> PUBLICACION1 { get; set; }
    }
}
