//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class adoptappEntities : DbContext
    {
        public adoptappEntities()
            : base("name=adoptappEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADOPCION> ADOPCION { get; set; }
        public virtual DbSet<INVENTARIO_REGISTROS> INVENTARIO_REGISTROS { get; set; }
        public virtual DbSet<MASCOTA> MASCOTA { get; set; }
        public virtual DbSet<PUBLICACION> PUBLICACION { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    }
}
