//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUBLICACION
    {
        public int ID_PUB { get; set; }
        public System.DateTime FECHA { get; set; }
        public byte[] FOTO { get; set; }
        public string DESCRIPCION { get; set; }
        public int U_RUT { get; set; }
        public string FOTO_URI { get; set; }
        public Nullable<int> ID_MASCOTA { get; set; }
    
        public virtual INVENTARIO_REGISTROS INVENTARIO_REGISTROS { get; set; }
        public virtual USUARIO USUARIO1 { get; set; }
        public virtual MASCOTA MASCOTA1 { get; set; }
    }
}
