//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUBLICACION
    {
        public int PUB_ID_PUBLICACION { get; set; }
        public System.DateTime PUB_FECHA { get; set; }
        public byte[] PUB_FOTO { get; set; }
        public string PUB_FOTO_URI { get; set; }
        public string PUB_DESCRIPCION { get; set; }
        public int PUB_USU_RUT { get; set; }
        public int MAS_ID_MASCOTA { get; set; }
        public string MAS_NOMBRE { get; set; }
        public int COM_ID_COMUNA { get; set; }
        public string COM_NOMBRE_COMUNA { get; set; }
    
        public virtual COMUNA COMUNA { get; set; }
        public virtual MASCOTA MASCOTA { get; set; }
    }
}
