//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int RUT { get; set; }
        public string DV { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<int> TELEFONO { get; set; }
        public string CORREO { get; set; }
        public string USE_NAME { get; set; }
        public string PASSWORD { get; set; }
    
        public virtual ADOPCION ADOPCION { get; set; }
        public virtual PUBLICACION PUBLICACION { get; set; }
    }
}
