//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int USU_RUT { get; set; }
        public string USU_DV { get; set; }
        public string USU_NOMBRE { get; set; }
        public int USU_TELEFONO { get; set; }
        public string USU_CORREO { get; set; }
        public string USU_USERNAME { get; set; }
        public string USU_PASSWORD { get; set; }
        public int COM_ID_COMUNA { get; set; }
        public string COM_NOMBRE_COMUNA { get; set; }
        public string USU_DIRECCION { get; set; }
        public bool USU_TIENE_MASCOTA_FLAG { get; set; }
        public System.DateTime USU_FECHA_NACIMIENTO { get; set; }
    
        public virtual COMUNA COMUNA { get; set; }
    }
}
